# Generated by Django 6.0.2 on 2026-03-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race_date', models.DateField()),
                ('course', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3')], max_length=2)),
                ('track_condition', models.CharField(blank=True, default='', max_length=10)),
                ('pace', models.CharField(blank=True, default='', max_length=1)),
                ('pace_comment', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=100)),
                ('gate', models.PositiveIntegerField(default=0)),
                ('number', models.PositiveIntegerField(default=0)),
                ('jockey', models.CharField(blank=True, default='', max_length=100)),
                ('run_style', models.CharField(choices=[('NIGE', '逃げ'), ('SENKO', '先行'), ('SASHI', '差し'), ('OIKOMI', '追込'), ('UNKNOWN', '不明')], default='UNKNOWN', max_length=10)),
                ('last1_agari_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('last2_agari_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('last3_agari_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_odds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='keibaapp_1.race')),
            ],
        ),
    ]
