# Generated by Django 6.0.2 on 2026-03-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keibaapp_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseentry',
            name='last1_corner4_pos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horseentry',
            name='last1_field_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horseentry',
            name='last2_corner4_pos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horseentry',
            name='last2_field_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horseentry',
            name='last3_corner4_pos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horseentry',
            name='last3_field_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
