# Generated by Django 6.0.2 on 2026-03-07 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keibaapp_1', '0002_horseentry_last1_corner4_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horseentry',
            name='run_style',
            field=models.CharField(choices=[('NIGE', '逃げ'), ('SENKO', '先行'), ('KOUI', '好位'), ('SASHI', '差し'), ('OIKOMI', '追込'), ('UNKNOWN', '不明')], default='UNKNOWN', max_length=10),
        ),
        migrations.CreateModel(
            name='EntryAnalysisSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=100)),
                ('horse_number', models.PositiveIntegerField(blank=True, null=True)),
                ('gate', models.PositiveIntegerField(blank=True, null=True)),
                ('jockey', models.CharField(blank=True, default='', max_length=100)),
                ('run_style', models.CharField(choices=[('NIGE', '逃げ'), ('SENKO', '先行'), ('KOUI', '好位'), ('SASHI', '差し'), ('OIKOMI', '追込'), ('UNKNOWN', '不明')], default='UNKNOWN', max_length=10)),
                ('corner4_index', models.FloatField(blank=True, null=True)),
                ('agari_avg_rank', models.FloatField(blank=True, null=True)),
                ('tempo_raw', models.FloatField(default=0.0)),
                ('tempo', models.FloatField(default=0.0)),
                ('pseudo_win_prob', models.FloatField(default=0.0)),
                ('value_index', models.FloatField(blank=True, null=True)),
                ('expected_odds', models.FloatField(blank=True, null=True)),
                ('rank_by_prob', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_by_value', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('horse_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_snapshots', to='keibaapp_1.horseentry')),
            ],
        ),
        migrations.CreateModel(
            name='EntryResultSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_position', models.PositiveIntegerField(blank=True, null=True)),
                ('corner4_actual', models.PositiveIntegerField(blank=True, null=True)),
                ('agari_actual_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('win_payoff', models.PositiveIntegerField(blank=True, null=True)),
                ('place_payoff', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_snapshot', to='keibaapp_1.entryanalysissnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='RaceAnalysisSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_pace', models.CharField(choices=[('S', 'スロー'), ('M', 'ミドル'), ('H', 'ハイ')], max_length=1)),
                ('pace_comment', models.CharField(blank=True, default='', max_length=255)),
                ('front_ratio', models.FloatField(default=0.0)),
                ('n_nige', models.IntegerField(default=0)),
                ('n_front', models.IntegerField(default=0)),
                ('pace_pressure', models.FloatField(default=0.0)),
                ('field_agari_avg', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, default='v1', max_length=30)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_snapshots', to='keibaapp_1.race')),
            ],
        ),
        migrations.AddField(
            model_name='entryanalysissnapshot',
            name='race_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_snapshots', to='keibaapp_1.raceanalysissnapshot'),
        ),
    ]
