# Generated by Django 6.0.2 on 2026-03-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keibaapp_1', '0003_alter_horseentry_run_style_entryanalysissnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseentry',
            name='last1_agari_3f',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horseentry',
            name='last2_agari_3f',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horseentry',
            name='last3_agari_3f',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
