# Generated by Django 6.0.2 on 2026-04-07 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keibaapp_1', '0004_horseentry_last1_agari_3f_horseentry_last2_agari_3f_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResultSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.PositiveIntegerField(blank=True, help_text='そのレースでの合計投資額', null=True)),
                ('return_amount', models.PositiveIntegerField(blank=True, help_text='そのレースでの合計払戻額', null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('race_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='race_result', to='keibaapp_1.raceanalysissnapshot')),
            ],
        ),
    ]
