# Generated by Django 6.0.2 on 2026-04-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keibaapp_1', '0005_raceresultsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='is_featured_this_week',
            field=models.BooleanField(default=False),
        ),
    ]
